# Generated by Django 5.1.6 on 2025-02-12 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersession',
            name='refresh_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
