# Generated by Django 5.1.6 on 2025-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_token_usersession_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
